import { Administration, Location, OrganLocation } from './types';

export const ADMS: Administration[] = ['Imbituba', 'Laguna', 'Tubarão', 'Criciúma'];

export const CHURCH_LOCATIONS: OrganLocation[] = [
  'Salão da igreja',
  'Sala de música',
  'Espaço infantil',
  'Outro'
];

export const INITIAL_LOCATIONS: Location[] = [
  // CRICIÚMA
  { id: 'c1', name: 'Santa Barbara - Criciúma', adm: 'Criciúma' },
  { id: 'c2', name: 'Mina do Toco - Criciúma', adm: 'Criciúma' },
  { id: 'c3', name: 'Monte Castelo - Criciúma', adm: 'Criciúma' },
  { id: 'c4', name: 'Nossa Senhora da Salete - Criciúma', adm: 'Criciúma' },
  { id: 'c5', name: 'Pinheirinho - Criciúma', adm: 'Criciúma' },
  { id: 'c6', name: 'Quarta Linha - Criciúma', adm: 'Criciúma' },
  { id: 'c7', name: 'São José - Rio Maina - Criciúma', adm: 'Criciúma' },
  { id: 'c8', name: 'São Sebastião - Criciúma', adm: 'Criciúma' },
  { id: 'c9', name: 'Vila Manaus - Criciúma', adm: 'Criciúma' },
  { id: 'c10', name: 'Coloninha - Araranguá', adm: 'Criciúma' },
  { id: 'c11', name: 'Jardim Sibele - Araranguá', adm: 'Criciúma' },
  { id: 'c12', name: 'Mato Alto - Araranguá', adm: 'Criciúma' },
  { id: 'c13', name: 'Mangueirinha - Balneário Arroio do Silva', adm: 'Criciúma' },
  { id: 'c14', name: 'Centro - Balneário Rincão', adm: 'Criciúma' },
  { id: 'c15', name: 'Jardim Elizabete - Cocal do Sul', adm: 'Criciúma' },
  { id: 'c16', name: 'Saturno - Forquilhinha', adm: 'Criciúma' },
  { id: 'c17', name: 'Raichask - Içara', adm: 'Criciúma' },
  { id: 'c18', name: 'Urussangua Velha - Içara', adm: 'Criciúma' },
  { id: 'c19', name: 'Vila Nova - Içara', adm: 'Criciúma' },
  { id: 'c20', name: 'Centro - Jacinto Machado', adm: 'Criciúma' },
  { id: 'c21', name: 'Vila Beatriz - Maracajá', adm: 'Criciúma' },
  { id: 'c22', name: 'Centro - Morro da Fumaça', adm: 'Criciúma' },
  { id: 'c23', name: 'Estação Cocal - Morro da Fumaça', adm: 'Criciúma' },
  { id: 'c24', name: 'Caravaggio - Nova Veneza', adm: 'Criciúma' },
  { id: 'c25', name: 'Progresso - Passo de Torres', adm: 'Criciúma' },
  { id: 'c26', name: 'Alvorada - Praia Grande', adm: 'Criciúma' },
  { id: 'c27', name: 'Rodovia SC-443 - KM 2 - Sangão', adm: 'Criciúma' },
  { id: 'c28', name: 'Parque Rosita - Santa Rosa do Sul', adm: 'Criciúma' },
  { id: 'c29', name: 'São Cristóvão - Santa Rosa do Sul', adm: 'Criciúma' },
  { id: 'c30', name: 'Vila Nova - Santa Rosa do Sul', adm: 'Criciúma' },
  { id: 'c31', name: 'Centro - Siderópolis', adm: 'Criciúma' },
  { id: 'c32', name: 'Vila Nova Brasília - Sombrio', adm: 'Criciúma' },
  { id: 'c33', name: 'Januária - Sombrio', adm: 'Criciúma' },
  { id: 'c34', name: 'Vila São Francisco - Sombrio', adm: 'Criciúma' },
  { id: 'c35', name: 'São Luiz - Timbé do Sul', adm: 'Criciúma' },
  { id: 'c36', name: 'Vila Esperança - Treviso', adm: 'Criciúma' },
  { id: 'c37', name: 'Vila Manentti - Turvo', adm: 'Criciúma' },
  { id: 'c38', name: 'De Villa - Urussangua', adm: 'Criciúma' },

  // IMBITUBA
  { id: 'i1', name: 'Vila Nova - Imbituba', adm: 'Imbituba' },
  { id: 'i2', name: 'Alto Arroio - Imbituba', adm: 'Imbituba' },
  { id: 'i3', name: 'Guaiuba - Imbituba', adm: 'Imbituba' },
  { id: 'i4', name: 'Ibiraquera - Imbituba', adm: 'Imbituba' },
  { id: 'i5', name: 'Roça Grande - Imbituba', adm: 'Imbituba' },
  { id: 'i6', name: 'Vila Nova Alvorada (Divinéia) - Imbituba', adm: 'Imbituba' },
  { id: 'i7', name: 'Areias de Palhocinha - Garopaba', adm: 'Imbituba' },
  { id: 'i8', name: 'Campo D\'una - Garopaba', adm: 'Imbituba' },
  { id: 'i9', name: 'Centro - Imaruí', adm: 'Imbituba' },
  { id: 'i10', name: 'Canguiri de Fora - Imaruí', adm: 'Imbituba' },
  { id: 'i11', name: 'Fazenda Rio das Garças - Imaruí', adm: 'Imbituba' },
  { id: 'i12', name: 'Laranjal - Imaruí', adm: 'Imbituba' },

  // LAGUNA
  { id: 'l1', name: 'Bentos - Laguna', adm: 'Laguna' },
  { id: 'l2', name: 'Cabeçudas - Laguna', adm: 'Laguna' },
  { id: 'l3', name: 'Campos Novos - Laguna', adm: 'Laguna' },
  { id: 'l4', name: 'Central - Laguna', adm: 'Laguna' },
  { id: 'l5', name: 'Cigana - Laguna', adm: 'Laguna' },
  { id: 'l6', name: 'Farol de Santa Marta - Laguna', adm: 'Laguna' },
  { id: 'l7', name: 'Mar Grosso - Laguna', adm: 'Laguna' },
  { id: 'l8', name: 'Morro Grande - Laguna', adm: 'Laguna' },
  { id: 'l9', name: 'Portinho - Laguna', adm: 'Laguna' },
  { id: 'l10', name: 'Ribeirão Pequeno - Laguna', adm: 'Laguna' },
  { id: 'l11', name: 'KM 37 - Pescaria Brava', adm: 'Laguna' },
  { id: 'l12', name: 'Ponta das Laranjeiras - Pescaria Brava', adm: 'Laguna' },

  // TUBARÃO
  { id: 't1', name: 'Andrino - Tubarão', adm: 'Tubarão' },
  { id: 't2', name: 'Bela Vista - Braço do Norte', adm: 'Tubarão' },
  { id: 't3', name: 'Bom Pastor - Tubarão', adm: 'Tubarão' },
  { id: 't4', name: 'Camacho - Jaguaruna', adm: 'Tubarão' },
  { id: 't5', name: 'Caruru - Tubarão', adm: 'Tubarão' },
  { id: 't6', name: 'Central - Tubarão', adm: 'Tubarão' },
  { id: 't7', name: 'Centro - Bom Jardim da Serra', adm: 'Tubarão' },
  { id: 't8', name: 'Centro - Capivari de Baixo', adm: 'Tubarão' },
  { id: 't9', name: 'Centro - Grão Pará', adm: 'Tubarão' },
  { id: 't10', name: 'Centro - Jaguaruna', adm: 'Tubarão' },
  { id: 't11', name: 'Centro - Lauro Muller', adm: 'Tubarão' },
  { id: 't12', name: 'Centro - Treze de Maio', adm: 'Tubarão' },
  { id: 't13', name: 'Comasa - Tubarão', adm: 'Tubarão' },
  { id: 't14', name: 'Copa - Jaguaruna', adm: 'Tubarão' },
  { id: 't15', name: 'Encosta do Sol - São Ludgero', adm: 'Tubarão' },
  { id: 't16', name: 'Estiva - Pescaria Brava', adm: 'Tubarão' },
  { id: 't17', name: 'Fabio Silva - Tubarão', adm: 'Tubarão' },
  { id: 't18', name: 'Guarda ME - Tubarão', adm: 'Tubarão' },
  { id: 't19', name: 'Guatá - Lauro Muller', adm: 'Tubarão' },
  { id: 't20', name: 'Humaitá Centro - Tubarão', adm: 'Tubarão' },
  { id: 't21', name: 'Humaitá de Cima - Tubarão', adm: 'Tubarão' },
  { id: 't22', name: 'Ilhota - Pedras Grandes', adm: 'Tubarão' },
  { id: 't23', name: 'Indaial - Gravatal', adm: 'Tubarão' },
  { id: 't24', name: 'KM 63 - Tubarão', adm: 'Tubarão' },
  { id: 't25', name: 'Mato Alto - Tubarão', adm: 'Tubarão' },
  { id: 't26', name: 'Pedrinhas - Pedras Grandes', adm: 'Tubarão' },
  { id: 't27', name: 'São Cristóvão - Tubarão', adm: 'Tubarão' },
  { id: 't28', name: 'São Geronimo - Orleans', adm: 'Tubarão' },
  { id: 't29', name: 'São Martinho - Tubarão', adm: 'Tubarão' },
  { id: 't30', name: 'São Martinho - São Martinho', adm: 'Tubarão' },
  { id: 't31', name: 'São Sebastião - Treze de Maio', adm: 'Tubarão' },
  { id: 't32', name: 'Sertão dos Correias - Tubarão', adm: 'Tubarão' },
  { id: 't33', name: 'Sertão dos Medeiros - Gravatal', adm: 'Tubarão' },
  { id: 't34', name: 'Termas do Gravatal - Gravatal', adm: 'Tubarão' },
  { id: 't35', name: 'Varzea das Canoas - Gravatal', adm: 'Tubarão' },
  { id: 't36', name: 'Vila São Francisco - Armazem', adm: 'Tubarão' },
];
